## Decision Tree Classifier on iris data
Build a Decision Tree Classifier model on iris dataframe where 
dependent variable is 'Species' and independent variables are the rest 
of the columns. Train and Test split 70:30

In [1]:
import numpy as np
import pandas as pd

In [7]:
x=pd.DataFrame(iris[{'SepalLengthCm','SepalWidthCm','PetalLengthCm','PetalWidthCm'}])
y=iris['Species']

In [2]:
# Load iris dataset
iris = pd.read_csv('iris.csv')
iris.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [19]:
iris.shape

(150, 6)

In [18]:
iris['Species'].unique()

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [8]:
# 70% records taken for Training the Model 30% of records for Testing the Model
# x_train -- Train set for the features
# x_test -- Test set for the features
# y_train -- Train set for the Target
# y_test -- Test set for the Target
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.30)

In [14]:
from sklearn.tree import DecisionTreeClassifier
# create an instance of the classifier
classifier = DecisionTreeClassifier()
classifier.fit(x_train,y_train)

DecisionTreeClassifier()

In [11]:
# y_pred consists of all predicted values
y_pred = classifier.predict(x_test)

In [12]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test,y_pred))
# All the values in diagonal are predcited correctly 15,13,13
# First Row -- Species of Iris-setosa'  15 of them classified correctly
# Second row -- Species of Iris-versicolor 13 classified correctly, 1 wrongly classified
# Third row -- Species of 'Iris-virginica' 13 classified correctly, 3 wrongly classified

[[15  0  0]
 [ 0 13  1]
 [ 0  3 13]]


In [13]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test,y_pred))

0.9111111111111111


In [ ]:
# Check on the Results
# Test Data 30 % of 150 records = 150x30% = 45 
# Accuracy = [15+13+13] / [15+13+1+3+13] 
# 41 out of 45 are classified correctly by the Model. omly 4 were wrongly classified.
# 41/45 = 0.91111111111111
# So Model Accuracy is above 90% which is a good model.